version: 2
jobs:
  build:
    working_directory: ~/TestCircleCi
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "./app/p1-master/build.gradle" }}-{{ checksum  "./app/p1-master/app/build.gradle" }}
      - run:
         name: Chmod permissions  
         command: sudo chmod +x ./app/p1-master/gradlew
      - run:
          name: Download Dependencies
          command: ./app/p1-master/gradlew dependencies
      - save_cache:
          paths:
            - ~/./app/p1-master/gradle
          key: jars-{{ checksum "./app/p1-master/build.gradle" }}-{{ checksum  "./app/p1-master/app/build.gradle" }}
      - run:
          name: Run UnitTest
          command: ./app/p1-master/gradlew 
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
 
    
