version: 2
jobs:
  build:
    working_directory: ~/testProject
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions  
         command: sudo chmod +x ./app/p1-master/gradlew
      - run:
          name: Download Dependencies
          command: ./app/p1-master/gradlew #androidDependencies
      - run:
          name: Run UnitTest
          command: ./app/p1-master/gradlew lint
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
 
    
     
  
    
